databases:
  - name: navweb-db
    plan: free
    databaseName: navweb
    user: navweb

services:
  - type: web
    name: navweb-backend
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile.backend
    dockerContext: .
    healthCheckPath: /healthcheck
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_PORT
        value: 10000
      - key: PORT
        value: 10000
      - key: POSTGRES_URL
        fromDatabase:
          name: navweb-db
          property: connectionString

  - type: web
    name: navweb-frontend
    runtime: static
    buildCommand: yarn install --immutable && yarn turbo run build --filter=frontend
    staticPublishPath: apps/frontend/build
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: true
    routes:
      - type: rewrite
        source: /api/*
        destination: https://navweb-backend.onrender.com/api/*
      - type: rewrite
        source: /*
        destination: /index.html
